### ISSUE TITLE
txt_NumAbbrevTh option ignored for days 10-19

### ISSUE THREAD

**Issue by tometzky** [jaime8111/jQueryEventCalendar#11]
When I translated `jQueryEventCalendar` to my language and set `txt_NumAbbrevTh` option to `.`, so it would use dot instead of `th`, it was ignored for days 10-19, and "th" was added.

This is caused by a bug in `num_abbrev_str(num)`:

    abbrev = 'th';

should be

    abbrev = eventsOpts.txt_NumAbbrevTh;

**Comment by jaime8111** [comment]
Thanks!

I just change it.

2015-02-24 14:40 GMT+01:00 tometzky <notifications@github.com>:

> When I translated jQueryEventCalendar to my language and set
> txt_NumAbbrevTh option to ., so it would use dot instead of th, it was
> ignored for days 10-19, and "th" was added.
>
> This is caused by a bug in num_abbrev_str(num):
>
> abbrev = 'th';
>
> should be
>
> abbrev = eventsOpts.txt_NumAbbrevTh;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaime8111/jQueryEventCalendar/issues/11>.
>



-- 

*Jaime Fernández*
· jaime8111@gmail.com
· Twitter <http://twitter.com/vissit>     · Facebook
<http://www.facebook.com/jaime8111>     ·  Linkedin
<http://www.linkedin.com/in/jaimefdez>
--------------------------------------------------------
