### ISSUE TITLE
Event colors

### ISSUE THREAD

**Issue by robfaas** [jaime8111/jQueryEventCalendar#9]
Is it possible to create events wich are shown in the calendar by different colors? So that you can have different event categories?

**Comment by jaime8111** [comment]
It is possible with CSS

In the JSON youcan define as many types of events as you want. This type is
added in each event element on the list. With CSS you can define a color
for each type.

2015-01-12 10:14 GMT+01:00 robfaas <notifications@github.com>:

> Is it possible to create events wich are shown in the calendar by
> different colors? So that you can have different event categories?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaime8111/jQueryEventCalendar/issues/9>.
>



-- 

*Jaime Fernández*
· jaime8111@gmail.com
· Twitter <http://twitter.com/vissit>     · Facebook
<http://www.facebook.com/jaime8111>     ·  Linkedin
<http://www.linkedin.com/in/jaimefdez>
--------------------------------------------------------

**Comment by robfaas** [comment]
Thanks! Great!
